apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: tasnim255/fitconnect-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/fitconnect_ai?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
            - name: APP_CORS_ALLOWED_ORIGINS
              value: http://localhost:30080,http://127.0.0.1:30080,http://192.168.65.136:30080
            - name: APP_CORS_ALLOWED_ORIGINS
              value: http://localhost:30080,http://127.0.0.1:30080
            - name: GROQ_API_KEY
              value: ""
          volumeMounts:
            - name: backend-uploads
              mountPath: /app/uploads
      volumes:
        - name: backend-uploads
          persistentVolumeClaim:
            claimName: backend-uploads-pvc

