apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-uploads-pvc
spec:
  storageClassName: manual
  volumeName: backend-uploads-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

