---
- name: Install Prometheus and Grafana
  hosts: master
  become: yes

  environment:
    KUBECONFIG: /home/tasnimoueslati/.kube/config

  tasks:
    - name: Add prometheus-community Helm repository
      command: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

    - name: Update Helm repositories
      command: helm repo update

    - name: Create monitoring namespace
      command: kubectl create namespace monitoring
      register: monitoring_namespace
      failed_when:
        - monitoring_namespace.rc != 0
        - "'AlreadyExists' not in monitoring_namespace.stderr"

    - name: Install kube-prometheus-stack
      command: helm upgrade --install my-kube-prometheus-stack prometheus-community/kube-prometheus-stack -n monitoring

    - name: Apply backend ServiceMonitor
      command: kubectl apply -f /home/tasnimoueslati/devops3/Fitness/k8s/monitoring-servicemonitor.yml

    - name: Apply backend PrometheusRule
      command: kubectl apply -f /home/tasnimoueslati/devops3/Fitness/k8s/monitoring-prometheusrule.yml

    - name: Check monitoring pods
      command: kubectl get pods -n monitoring
      register: monitoring_pods

    - name: Show monitoring pods
      debug:
        var: monitoring_pods.stdout_lines
